---
name: Terraform Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: "1.12.1"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
